version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    assignees:
      - "parafoxia"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    labels:
      - "dependencies"
    rebase-strategy: auto
    reviewers:
        - "parafoxia"
    target-branch: "task/version-2"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "parafoxia"
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-patch"]
    labels:
      - "dependencies"
    rebase-strategy: auto
    reviewers:
        - "parafoxia"
    target-branch: "task/version-2"
